name: quotely
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

##############################################################################################################################
### Scripts
scripts:
  # run is a default script. To use it, simply type
  # in the command line: "rps" - that's all!
  model_build: "dart run build_runner build --delete-conflicting-outputs"
  pod: "cd ios && pod install && cd .."
  clean_get: "flutter clean && flutter pub get"

### Scripts
##############################################################################################################################
environment:
  sdk: '>=3.4.4 <4.0.0'
##############################################################################################################################
###
### Dependencies
###
dependencies:
  animated_custom_dropdown: ^3.0.0
  another_flushbar: ^1.12.30
  auto_route: ^7.8.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  cookie_jar: ^4.0.8
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  easy_localization: ^3.0.3
  envied: ^0.3.0+3
  equatable: ^2.0.0
  firebase_core: ^2.25.4
  flutter:
    sdk: flutter
  flutter_animated_dialog:
    path: lib/vendor/animated_dialog/flutter_animated_dialog
  flutter_box_transform: ^0.4.2
  flutter_local_notifications: ^17.2.1+2
  flutter_slidable: ^3.0.1
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  google_mobile_ads: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_pixels: ^3.0.1
  injectable: ^2.3.0
  internet_connection_checker: ^1.0.0+1
  logger: ^2.0.2+1
  path_provider: ^2.1.2
  rest_api_package:
    git:
      url: https://github.com/mrasityilmaz/rest_api_package.git
  sliver_tools: ^0.2.12
  stacked: ^3.4.1
  stacked_themes: ^0.3.12
  uuid: ^4.3.3
  visibility_detector: ^0.4.0+2
  flutter_timezone: ^2.1.0
  permission_handler: ^11.3.1
  safe_int_id: ^1.1.1

###
### Dependencies
###
##############################################################################################################################
##############################################################################################################################
###
### Dev Dependencies
###
dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6

  ###
  ### Lint
  ###
  envied_generator: ^0.3.0+3
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  hive_generator: ^2.0.1

  ###
  ### Injection Generator
  ###
  injectable_generator: ^2.4.0

  ###
  ### Json Serialization
  ###
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0
###
### Dev Dependencies
###
##############################################################################################################################
flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/translations/
    - assets/backgrounds/
    - assets/new_category_icons/
    - assets/quotes/
    - assets/quotes/categories/
    - assets/quotes/en/
    - assets/quotes/tr/
    - test/fixtures/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
