// ignore_for_file: public_member_api_docs,constant_identifier_names,type=lint,unused_element,unused_field
import 'package:flutter/foundation.dart';

//
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// Generated by flutter-assets-generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

@immutable
final class Assets {
  Assets._();
  static final _Backgrounds backgrounds = _Backgrounds._();
  static final _Category_icons category_icons = _Category_icons._();
  static final _New_category_icons new_category_icons = _New_category_icons._();
  static final _Quotes quotes = _Quotes._();
  static final _Translations translations = _Translations._();

  static const String crow_front_premium_png = 'assets/crow-front-premium.png';

}

@immutable
final class _Backgrounds {
  _Backgrounds._();

  final String n1_webp = 'assets/backgrounds/1.webp';
  final String n10_webp = 'assets/backgrounds/10.webp';
  final String n100_webp = 'assets/backgrounds/100.webp';
  final String n101_webp = 'assets/backgrounds/101.webp';
  final String n102_webp = 'assets/backgrounds/102.webp';
  final String n103_webp = 'assets/backgrounds/103.webp';
  final String n104_webp = 'assets/backgrounds/104.webp';
  final String n105_webp = 'assets/backgrounds/105.webp';
  final String n106_webp = 'assets/backgrounds/106.webp';
  final String n107_webp = 'assets/backgrounds/107.webp';
  final String n108_webp = 'assets/backgrounds/108.webp';
  final String n109_webp = 'assets/backgrounds/109.webp';
  final String n11_webp = 'assets/backgrounds/11.webp';
  final String n110_webp = 'assets/backgrounds/110.webp';
  final String n111_webp = 'assets/backgrounds/111.webp';
  final String n112_webp = 'assets/backgrounds/112.webp';
  final String n113_webp = 'assets/backgrounds/113.webp';
  final String n114_webp = 'assets/backgrounds/114.webp';
  final String n115_webp = 'assets/backgrounds/115.webp';
  final String n116_webp = 'assets/backgrounds/116.webp';
  final String n117_webp = 'assets/backgrounds/117.webp';
  final String n118_webp = 'assets/backgrounds/118.webp';
  final String n119_webp = 'assets/backgrounds/119.webp';
  final String n12_webp = 'assets/backgrounds/12.webp';
  final String n120_webp = 'assets/backgrounds/120.webp';
  final String n121_webp = 'assets/backgrounds/121.webp';
  final String n122_webp = 'assets/backgrounds/122.webp';
  final String n123_webp = 'assets/backgrounds/123.webp';
  final String n124_webp = 'assets/backgrounds/124.webp';
  final String n13_webp = 'assets/backgrounds/13.webp';
  final String n14_webp = 'assets/backgrounds/14.webp';
  final String n15_webp = 'assets/backgrounds/15.webp';
  final String n16_webp = 'assets/backgrounds/16.webp';
  final String n17_webp = 'assets/backgrounds/17.webp';
  final String n18_webp = 'assets/backgrounds/18.webp';
  final String n19_webp = 'assets/backgrounds/19.webp';
  final String n2_webp = 'assets/backgrounds/2.webp';
  final String n20_webp = 'assets/backgrounds/20.webp';
  final String n21_webp = 'assets/backgrounds/21.webp';
  final String n22_webp = 'assets/backgrounds/22.webp';
  final String n23_webp = 'assets/backgrounds/23.webp';
  final String n24_webp = 'assets/backgrounds/24.webp';
  final String n25_webp = 'assets/backgrounds/25.webp';
  final String n26_webp = 'assets/backgrounds/26.webp';
  final String n27_webp = 'assets/backgrounds/27.webp';
  final String n28_webp = 'assets/backgrounds/28.webp';
  final String n29_webp = 'assets/backgrounds/29.webp';
  final String n3_webp = 'assets/backgrounds/3.webp';
  final String n30_webp = 'assets/backgrounds/30.webp';
  final String n31_webp = 'assets/backgrounds/31.webp';
  final String n32_webp = 'assets/backgrounds/32.webp';
  final String n33_webp = 'assets/backgrounds/33.webp';
  final String n34_webp = 'assets/backgrounds/34.webp';
  final String n35_webp = 'assets/backgrounds/35.webp';
  final String n36_webp = 'assets/backgrounds/36.webp';
  final String n37_webp = 'assets/backgrounds/37.webp';
  final String n38_webp = 'assets/backgrounds/38.webp';
  final String n39_webp = 'assets/backgrounds/39.webp';
  final String n4_webp = 'assets/backgrounds/4.webp';
  final String n40_webp = 'assets/backgrounds/40.webp';
  final String n41_webp = 'assets/backgrounds/41.webp';
  final String n42_webp = 'assets/backgrounds/42.webp';
  final String n43_webp = 'assets/backgrounds/43.webp';
  final String n44_webp = 'assets/backgrounds/44.webp';
  final String n45_webp = 'assets/backgrounds/45.webp';
  final String n46_webp = 'assets/backgrounds/46.webp';
  final String n47_webp = 'assets/backgrounds/47.webp';
  final String n48_webp = 'assets/backgrounds/48.webp';
  final String n49_webp = 'assets/backgrounds/49.webp';
  final String n5_webp = 'assets/backgrounds/5.webp';
  final String n50_webp = 'assets/backgrounds/50.webp';
  final String n51_webp = 'assets/backgrounds/51.webp';
  final String n52_webp = 'assets/backgrounds/52.webp';
  final String n53_webp = 'assets/backgrounds/53.webp';
  final String n54_webp = 'assets/backgrounds/54.webp';
  final String n55_webp = 'assets/backgrounds/55.webp';
  final String n56_webp = 'assets/backgrounds/56.webp';
  final String n57_webp = 'assets/backgrounds/57.webp';
  final String n58_webp = 'assets/backgrounds/58.webp';
  final String n59_webp = 'assets/backgrounds/59.webp';
  final String n6_webp = 'assets/backgrounds/6.webp';
  final String n60_webp = 'assets/backgrounds/60.webp';
  final String n61_webp = 'assets/backgrounds/61.webp';
  final String n62_webp = 'assets/backgrounds/62.webp';
  final String n63_webp = 'assets/backgrounds/63.webp';
  final String n64_webp = 'assets/backgrounds/64.webp';
  final String n65_webp = 'assets/backgrounds/65.webp';
  final String n66_webp = 'assets/backgrounds/66.webp';
  final String n67_webp = 'assets/backgrounds/67.webp';
  final String n68_webp = 'assets/backgrounds/68.webp';
  final String n69_webp = 'assets/backgrounds/69.webp';
  final String n7_webp = 'assets/backgrounds/7.webp';
  final String n70_webp = 'assets/backgrounds/70.webp';
  final String n71_webp = 'assets/backgrounds/71.webp';
  final String n72_webp = 'assets/backgrounds/72.webp';
  final String n73_webp = 'assets/backgrounds/73.webp';
  final String n74_webp = 'assets/backgrounds/74.webp';
  final String n75_webp = 'assets/backgrounds/75.webp';
  final String n76_webp = 'assets/backgrounds/76.webp';
  final String n77_webp = 'assets/backgrounds/77.webp';
  final String n78_webp = 'assets/backgrounds/78.webp';
  final String n79_webp = 'assets/backgrounds/79.webp';
  final String n8_webp = 'assets/backgrounds/8.webp';
  final String n80_webp = 'assets/backgrounds/80.webp';
  final String n81_webp = 'assets/backgrounds/81.webp';
  final String n82_webp = 'assets/backgrounds/82.webp';
  final String n83_webp = 'assets/backgrounds/83.webp';
  final String n84_webp = 'assets/backgrounds/84.webp';
  final String n85_webp = 'assets/backgrounds/85.webp';
  final String n86_webp = 'assets/backgrounds/86.webp';
  final String n87_webp = 'assets/backgrounds/87.webp';
  final String n88_webp = 'assets/backgrounds/88.webp';
  final String n89_webp = 'assets/backgrounds/89.webp';
  final String n9_webp = 'assets/backgrounds/9.webp';
  final String n90_webp = 'assets/backgrounds/90.webp';
  final String n91_webp = 'assets/backgrounds/91.webp';
  final String n92_webp = 'assets/backgrounds/92.webp';
  final String n93_webp = 'assets/backgrounds/93.webp';
  final String n94_webp = 'assets/backgrounds/94.webp';
  final String n95_webp = 'assets/backgrounds/95.webp';
  final String n96_webp = 'assets/backgrounds/96.webp';
  final String n97_webp = 'assets/backgrounds/97.webp';
  final String n98_webp = 'assets/backgrounds/98.webp';
  final String n99_webp = 'assets/backgrounds/99.webp';

}

@immutable
final class _Category_icons {
  _Category_icons._();

  final String n10_webp = 'assets/category_icons/10.webp';
  final String n100_webp = 'assets/category_icons/100.webp';
  final String n101_webp = 'assets/category_icons/101.webp';
  final String n102_webp = 'assets/category_icons/102.webp';
  final String n11_webp = 'assets/category_icons/11.webp';
  final String n12_webp = 'assets/category_icons/12.webp';
  final String n13_webp = 'assets/category_icons/13.webp';
  final String n14_webp = 'assets/category_icons/14.webp';
  final String n15_webp = 'assets/category_icons/15.webp';
  final String n16_webp = 'assets/category_icons/16.webp';
  final String n17_webp = 'assets/category_icons/17.webp';
  final String n18_webp = 'assets/category_icons/18.webp';
  final String n19_webp = 'assets/category_icons/19.webp';
  final String n20_webp = 'assets/category_icons/20.webp';
  final String n21_webp = 'assets/category_icons/21.webp';
  final String n22_webp = 'assets/category_icons/22.webp';
  final String n23_webp = 'assets/category_icons/23.webp';
  final String n24_webp = 'assets/category_icons/24.webp';
  final String n25_webp = 'assets/category_icons/25.webp';
  final String n26_webp = 'assets/category_icons/26.webp';
  final String n27_webp = 'assets/category_icons/27.webp';
  final String n28_webp = 'assets/category_icons/28.webp';
  final String n29_webp = 'assets/category_icons/29.webp';
  final String n30_webp = 'assets/category_icons/30.webp';
  final String n31_webp = 'assets/category_icons/31.webp';
  final String n32_webp = 'assets/category_icons/32.webp';
  final String n33_webp = 'assets/category_icons/33.webp';
  final String n34_webp = 'assets/category_icons/34.webp';
  final String n35_webp = 'assets/category_icons/35.webp';
  final String n36_webp = 'assets/category_icons/36.webp';
  final String n37_webp = 'assets/category_icons/37.webp';
  final String n38_webp = 'assets/category_icons/38.webp';
  final String n39_webp = 'assets/category_icons/39.webp';
  final String n4_webp = 'assets/category_icons/4.webp';
  final String n40_webp = 'assets/category_icons/40.webp';
  final String n41_webp = 'assets/category_icons/41.webp';
  final String n42_webp = 'assets/category_icons/42.webp';
  final String n43_webp = 'assets/category_icons/43.webp';
  final String n44_webp = 'assets/category_icons/44.webp';
  final String n45_webp = 'assets/category_icons/45.webp';
  final String n46_webp = 'assets/category_icons/46.webp';
  final String n47_webp = 'assets/category_icons/47.webp';
  final String n48_webp = 'assets/category_icons/48.webp';
  final String n49_webp = 'assets/category_icons/49.webp';
  final String n5_webp = 'assets/category_icons/5.webp';
  final String n50_webp = 'assets/category_icons/50.webp';
  final String n51_webp = 'assets/category_icons/51.webp';
  final String n52_webp = 'assets/category_icons/52.webp';
  final String n53_webp = 'assets/category_icons/53.webp';
  final String n54_webp = 'assets/category_icons/54.webp';
  final String n55_webp = 'assets/category_icons/55.webp';
  final String n56_webp = 'assets/category_icons/56.webp';
  final String n57_webp = 'assets/category_icons/57.webp';
  final String n58_webp = 'assets/category_icons/58.webp';
  final String n59_webp = 'assets/category_icons/59.webp';
  final String n6_webp = 'assets/category_icons/6.webp';
  final String n60_webp = 'assets/category_icons/60.webp';
  final String n61_webp = 'assets/category_icons/61.webp';
  final String n62_webp = 'assets/category_icons/62.webp';
  final String n63_webp = 'assets/category_icons/63.webp';
  final String n64_webp = 'assets/category_icons/64.webp';
  final String n65_webp = 'assets/category_icons/65.webp';
  final String n66_webp = 'assets/category_icons/66.webp';
  final String n67_webp = 'assets/category_icons/67.webp';
  final String n68_webp = 'assets/category_icons/68.webp';
  final String n69_webp = 'assets/category_icons/69.webp';
  final String n7_webp = 'assets/category_icons/7.webp';
  final String n70_webp = 'assets/category_icons/70.webp';
  final String n71_webp = 'assets/category_icons/71.webp';
  final String n72_webp = 'assets/category_icons/72.webp';
  final String n73_webp = 'assets/category_icons/73.webp';
  final String n74_webp = 'assets/category_icons/74.webp';
  final String n75_webp = 'assets/category_icons/75.webp';
  final String n76_webp = 'assets/category_icons/76.webp';
  final String n77_webp = 'assets/category_icons/77.webp';
  final String n78_webp = 'assets/category_icons/78.webp';
  final String n79_webp = 'assets/category_icons/79.webp';
  final String n8_webp = 'assets/category_icons/8.webp';
  final String n80_webp = 'assets/category_icons/80.webp';
  final String n81_webp = 'assets/category_icons/81.webp';
  final String n82_webp = 'assets/category_icons/82.webp';
  final String n83_webp = 'assets/category_icons/83.webp';
  final String n84_webp = 'assets/category_icons/84.webp';
  final String n85_webp = 'assets/category_icons/85.webp';
  final String n86_webp = 'assets/category_icons/86.webp';
  final String n87_webp = 'assets/category_icons/87.webp';
  final String n88_webp = 'assets/category_icons/88.webp';
  final String n89_webp = 'assets/category_icons/89.webp';
  final String n9_webp = 'assets/category_icons/9.webp';
  final String n90_webp = 'assets/category_icons/90.webp';
  final String n91_webp = 'assets/category_icons/91.webp';
  final String n92_webp = 'assets/category_icons/92.webp';
  final String n93_webp = 'assets/category_icons/93.webp';
  final String n94_webp = 'assets/category_icons/94.webp';
  final String n95_webp = 'assets/category_icons/95.webp';
  final String n96_webp = 'assets/category_icons/96.webp';
  final String n97_webp = 'assets/category_icons/97.webp';
  final String n98_webp = 'assets/category_icons/98.webp';
  final String n99_webp = 'assets/category_icons/99.webp';
  final String art_webp = 'assets/category_icons/art.webp';

}

@immutable
final class _New_category_icons {
  _New_category_icons._();

  final String anger_control_webp = 'assets/new_category_icons/anger_control.webp';
  final String art_webp = 'assets/new_category_icons/art.webp';
  final String attitude_webp = 'assets/new_category_icons/attitude.webp';
  final String be_strong_webp = 'assets/new_category_icons/be_strong.webp';
  final String be_yourself_webp = 'assets/new_category_icons/be_yourself.webp';
  final String bodybuilding_webp = 'assets/new_category_icons/bodybuilding.webp';
  final String business_webp = 'assets/new_category_icons/business.webp';
  final String calm_webp = 'assets/new_category_icons/calm.webp';
  final String chance_webp = 'assets/new_category_icons/chance.webp';
  final String communication_webp = 'assets/new_category_icons/communication.webp';
  final String computer_webp = 'assets/new_category_icons/computer.webp';
  final String courage_webp = 'assets/new_category_icons/courage.webp';
  final String dating_webp = 'assets/new_category_icons/dating.webp';
  final String dissappointment_webp = 'assets/new_category_icons/dissappointment.webp';
  final String dreams_webp = 'assets/new_category_icons/dreams.webp';
  final String education_webp = 'assets/new_category_icons/education.webp';
  final String enjoy_the_moment_webp = 'assets/new_category_icons/enjoy_the_moment.webp';
  final String entrepreneurs_webp = 'assets/new_category_icons/entrepreneurs.webp';
  final String equality_webp = 'assets/new_category_icons/equality.webp';
  final String experience_webp = 'assets/new_category_icons/experience.webp';
  final String failure_webp = 'assets/new_category_icons/failure.webp';
  final String faith_webp = 'assets/new_category_icons/faith.webp';
  final String falling_love_webp = 'assets/new_category_icons/falling_love.webp';
  final String family_webp = 'assets/new_category_icons/family.webp';
  final String favorites_webp = 'assets/new_category_icons/favorites.webp';
  final String fear_webp = 'assets/new_category_icons/fear.webp';
  final String finance_webp = 'assets/new_category_icons/finance.webp';
  final String forgiveness_webp = 'assets/new_category_icons/forgiveness.webp';
  final String freedom_webp = 'assets/new_category_icons/freedom.webp';
  final String friendship_webp = 'assets/new_category_icons/friendship.webp';
  final String funny_webp = 'assets/new_category_icons/funny.webp';
  final String general_webp = 'assets/new_category_icons/general.webp';
  final String god_webp = 'assets/new_category_icons/god.webp';
  final String growth_webp = 'assets/new_category_icons/growth.webp';
  final String happiness_webp = 'assets/new_category_icons/happiness.webp';
  final String haters_webp = 'assets/new_category_icons/haters.webp';
  final String health_webp = 'assets/new_category_icons/health.webp';
  final String heartbroken_webp = 'assets/new_category_icons/heartbroken.webp';
  final String history_webp = 'assets/new_category_icons/history.webp';
  final String hope_webp = 'assets/new_category_icons/hope.webp';
  final String imagination_webp = 'assets/new_category_icons/imagination.webp';
  final String inner_peace_webp = 'assets/new_category_icons/inner_peace.webp';
  final String inspirational_webp = 'assets/new_category_icons/inspirational.webp';
  final String intelligence_webp = 'assets/new_category_icons/intelligence.webp';
  final String jealousy_webp = 'assets/new_category_icons/jealousy.webp';
  final String knowledge_webp = 'assets/new_category_icons/knowledge.webp';
  final String leadership_webp = 'assets/new_category_icons/leadership.webp';
  final String learning_webp = 'assets/new_category_icons/learning.webp';
  final String life_webp = 'assets/new_category_icons/life.webp';
  final String loneliness_webp = 'assets/new_category_icons/loneliness.webp';
  final String love_yourself_webp = 'assets/new_category_icons/love_yourself.webp';
  final String marriage_webp = 'assets/new_category_icons/marriage.webp';
  final String minimalism_webp = 'assets/new_category_icons/minimalism.webp';
  final String money_webp = 'assets/new_category_icons/money.webp';
  final String motivational_webp = 'assets/new_category_icons/motivational.webp';
  final String music_webp = 'assets/new_category_icons/music.webp';
  final String myquotes_webp = 'assets/new_category_icons/myquotes.webp';
  final String nature_webp = 'assets/new_category_icons/nature.webp';
  final String new_beginnings_webp = 'assets/new_category_icons/new_beginnings.webp';
  final String pain_webp = 'assets/new_category_icons/pain.webp';
  final String patience_webp = 'assets/new_category_icons/patience.webp';
  final String pet_webp = 'assets/new_category_icons/pet.webp';
  final String philosophy_webp = 'assets/new_category_icons/philosophy.webp';
  final String poetry_webp = 'assets/new_category_icons/poetry.webp';
  final String positive_thinking_webp = 'assets/new_category_icons/positive_thinking.webp';
  final String power_webp = 'assets/new_category_icons/power.webp';
  final String relations_webp = 'assets/new_category_icons/relations.webp';
  final String religion_webp = 'assets/new_category_icons/religion.webp';
  final String respect_webp = 'assets/new_category_icons/respect.webp';
  final String romantic_webp = 'assets/new_category_icons/romantic.webp';
  final String sadness_webp = 'assets/new_category_icons/sadness.webp';
  final String science_webp = 'assets/new_category_icons/science.webp';
  final String self_discipline_webp = 'assets/new_category_icons/self_discipline.webp';
  final String society_webp = 'assets/new_category_icons/society.webp';
  final String space_webp = 'assets/new_category_icons/space.webp';
  final String sports_webp = 'assets/new_category_icons/sports.webp';
  final String start_change_webp = 'assets/new_category_icons/start_change.webp';
  final String strength_webp = 'assets/new_category_icons/strength.webp';
  final String success_webp = 'assets/new_category_icons/success.webp';
  final String sympathy_webp = 'assets/new_category_icons/sympathy.webp';
  final String technology_webp = 'assets/new_category_icons/technology.webp';
  final String thankful_webp = 'assets/new_category_icons/thankful.webp';
  final String time_webp = 'assets/new_category_icons/time.webp';
  final String travel_webp = 'assets/new_category_icons/travel.webp';
  final String trust_webp = 'assets/new_category_icons/trust.webp';
  final String truth_webp = 'assets/new_category_icons/truth.webp';
  final String uncertainty_webp = 'assets/new_category_icons/uncertainty.webp';
  final String weight_loss_webp = 'assets/new_category_icons/weight_loss.webp';
  final String wisdom_webp = 'assets/new_category_icons/wisdom.webp';
  final String work_webp = 'assets/new_category_icons/work.webp';
  final String work_out_webp = 'assets/new_category_icons/work_out.webp';

}

@immutable
final class _Categories {
  _Categories._();

  final String anger_control_quotes_json = 'assets/quotes/categories/anger_control_quotes.json';
  final String art_quotes_json = 'assets/quotes/categories/art_quotes.json';
  final String attitude_quotes_json = 'assets/quotes/categories/attitude_quotes.json';
  final String be_strong_quotes_json = 'assets/quotes/categories/be_strong_quotes.json';
  final String be_yourself_quotes_json = 'assets/quotes/categories/be_yourself_quotes.json';
  final String bodybuilding_quotes_json = 'assets/quotes/categories/bodybuilding_quotes.json';
  final String business_quotes_json = 'assets/quotes/categories/business_quotes.json';
  final String calm_quotes_json = 'assets/quotes/categories/calm_quotes.json';
  final String chance_quotes_json = 'assets/quotes/categories/chance_quotes.json';
  final String communication_quotes_json = 'assets/quotes/categories/communication_quotes.json';
  final String computer_quotes_json = 'assets/quotes/categories/computer_quotes.json';
  final String courage_quotes_json = 'assets/quotes/categories/courage_quotes.json';
  final String dating_quotes_json = 'assets/quotes/categories/dating_quotes.json';
  final String dissappointment_quotes_json = 'assets/quotes/categories/dissappointment_quotes.json';
  final String dreams_quotes_json = 'assets/quotes/categories/dreams_quotes.json';
  final String education_quotes_json = 'assets/quotes/categories/education_quotes.json';
  final String enjoy_the_moment_quotes_json = 'assets/quotes/categories/enjoy_the_moment_quotes.json';
  final String entrepreneurs_quotes_json = 'assets/quotes/categories/entrepreneurs_quotes.json';
  final String equality_quotes_json = 'assets/quotes/categories/equality_quotes.json';
  final String experience_quotes_json = 'assets/quotes/categories/experience_quotes.json';
  final String failure_quotes_json = 'assets/quotes/categories/failure_quotes.json';
  final String faith_quotes_json = 'assets/quotes/categories/faith_quotes.json';
  final String falling_love_quotes_json = 'assets/quotes/categories/falling_love_quotes.json';
  final String family_quotes_json = 'assets/quotes/categories/family_quotes.json';
  final String fear_quotes_json = 'assets/quotes/categories/fear_quotes.json';
  final String finance_quotes_json = 'assets/quotes/categories/finance_quotes.json';
  final String forgiveness_quotes_json = 'assets/quotes/categories/forgiveness_quotes.json';
  final String freedom_quotes_json = 'assets/quotes/categories/freedom_quotes.json';
  final String friendship_quotes_json = 'assets/quotes/categories/friendship_quotes.json';
  final String funny_quotes_json = 'assets/quotes/categories/funny_quotes.json';
  final String god_quotes_json = 'assets/quotes/categories/god_quotes.json';
  final String growth_quotes_json = 'assets/quotes/categories/growth_quotes.json';
  final String happiness_quotes_json = 'assets/quotes/categories/happiness_quotes.json';
  final String haters_quotes_json = 'assets/quotes/categories/haters_quotes.json';
  final String health_quotes_json = 'assets/quotes/categories/health_quotes.json';
  final String heartbroken_quotes_json = 'assets/quotes/categories/heartbroken_quotes.json';
  final String history_quotes_json = 'assets/quotes/categories/history_quotes.json';
  final String hope_quotes_json = 'assets/quotes/categories/hope_quotes.json';
  final String imagination_quotes_json = 'assets/quotes/categories/imagination_quotes.json';
  final String inner_peace_quotes_json = 'assets/quotes/categories/inner_peace_quotes.json';
  final String inspirational_quotes_json = 'assets/quotes/categories/inspirational_quotes.json';
  final String intelligence_quotes_json = 'assets/quotes/categories/intelligence_quotes.json';
  final String jealousy_quotes_json = 'assets/quotes/categories/jealousy_quotes.json';
  final String knowledge_quotes_json = 'assets/quotes/categories/knowledge_quotes.json';
  final String leadership_quotes_json = 'assets/quotes/categories/leadership_quotes.json';
  final String learning_quotes_json = 'assets/quotes/categories/learning_quotes.json';
  final String life_quotes_json = 'assets/quotes/categories/life_quotes.json';
  final String loneliness_quotes_json = 'assets/quotes/categories/loneliness_quotes.json';
  final String love_yourself_quotes_json = 'assets/quotes/categories/love_yourself_quotes.json';
  final String marriage_quotes_json = 'assets/quotes/categories/marriage_quotes.json';
  final String minimalism_quotes_json = 'assets/quotes/categories/minimalism_quotes.json';
  final String money_quotes_json = 'assets/quotes/categories/money_quotes.json';
  final String motivational_quotes_json = 'assets/quotes/categories/motivational_quotes.json';
  final String music_quotes_json = 'assets/quotes/categories/music_quotes.json';
  final String nature_quotes_json = 'assets/quotes/categories/nature_quotes.json';
  final String new_beginnings_quotes_json = 'assets/quotes/categories/new_beginnings_quotes.json';
  final String pain_quotes_json = 'assets/quotes/categories/pain_quotes.json';
  final String patience_quotes_json = 'assets/quotes/categories/patience_quotes.json';
  final String pet_quotes_json = 'assets/quotes/categories/pet_quotes.json';
  final String philosophy_quotes_json = 'assets/quotes/categories/philosophy_quotes.json';
  final String poetry_quotes_json = 'assets/quotes/categories/poetry_quotes.json';
  final String positive_thinking_quotes_json = 'assets/quotes/categories/positive_thinking_quotes.json';
  final String power_quotes_json = 'assets/quotes/categories/power_quotes.json';
  final String relations_quotes_json = 'assets/quotes/categories/relations_quotes.json';
  final String religion_quotes_json = 'assets/quotes/categories/religion_quotes.json';
  final String respect_quotes_json = 'assets/quotes/categories/respect_quotes.json';
  final String romantic_quotes_json = 'assets/quotes/categories/romantic_quotes.json';
  final String sadness_quotes_json = 'assets/quotes/categories/sadness_quotes.json';
  final String science_quotes_json = 'assets/quotes/categories/science_quotes.json';
  final String self_discipline_quotes_json = 'assets/quotes/categories/self-discipline_quotes.json';
  final String society_quotes_json = 'assets/quotes/categories/society_quotes.json';
  final String space_quotes_json = 'assets/quotes/categories/space_quotes.json';
  final String sports_quotes_json = 'assets/quotes/categories/sports_quotes.json';
  final String start_change_quotes_json = 'assets/quotes/categories/start_change_quotes.json';
  final String strength_quotes_json = 'assets/quotes/categories/strength_quotes.json';
  final String success_quotes_json = 'assets/quotes/categories/success_quotes.json';
  final String sympathy_quotes_json = 'assets/quotes/categories/sympathy_quotes.json';
  final String technology_quotes_json = 'assets/quotes/categories/technology_quotes.json';
  final String thankful_quotes_json = 'assets/quotes/categories/thankful_quotes.json';
  final String time_quotes_json = 'assets/quotes/categories/time_quotes.json';
  final String travel_quotes_json = 'assets/quotes/categories/travel_quotes.json';
  final String trust_quotes_json = 'assets/quotes/categories/trust_quotes.json';
  final String truth_quotes_json = 'assets/quotes/categories/truth_quotes.json';
  final String uncertainty_quotes_json = 'assets/quotes/categories/uncertainty_quotes.json';
  final String weight_loss_quotes_json = 'assets/quotes/categories/weight_loss_quotes.json';
  final String wisdom_quotes_json = 'assets/quotes/categories/wisdom_quotes.json';
  final String work_out_quotes_json = 'assets/quotes/categories/work_out_quotes.json';
  final String work_quotes_json = 'assets/quotes/categories/work_quotes.json';

}

@immutable
final class _En {
  _En._();

  final String boost_quotes_en_json = 'assets/quotes/en/boost_quotes_en.json';
  final String notification_quotes_en_json = 'assets/quotes/en/notification_quotes_en.json';

}

@immutable
final class _Tr {
  _Tr._();

  final String boost_quotes_tr_json = 'assets/quotes/tr/boost_quotes_tr.json';
  final String notification_quotes_tr_json = 'assets/quotes/tr/notification_quotes_tr.json';

}

@immutable
final class _Quotes {
  _Quotes._();
  final _Categories categories = _Categories._();
  final _En en = _En._();
  final _Tr tr = _Tr._();


}

@immutable
final class _Translations {
  _Translations._();

  final String en_json = 'assets/translations/en.json';
  final String tr_json = 'assets/translations/tr.json';

}

