// GENERATED CODE - DO WHATEVER YOU WANT WITH IT
// **************************************************************************
// Total assets: 104
// Generated by flutter_assets_generator extension for VS Code
// @mrasityilmaz
// **************************************************************************

class Assets {
  static const String c0_webp = 'assets/category_icons/0.webp';

  static const String c1_webp = 'assets/category_icons/1.webp';

  static const String c10_webp = 'assets/category_icons/10.webp';

  static const String c100_webp = 'assets/category_icons/100.webp';

  static const String c101_webp = 'assets/category_icons/101.webp';

  static const String c102_webp = 'assets/category_icons/102.webp';

  static const String c11_webp = 'assets/category_icons/11.webp';

  static const String c12_webp = 'assets/category_icons/12.webp';

  static const String c13_webp = 'assets/category_icons/13.webp';

  static const String c14_webp = 'assets/category_icons/14.webp';

  static const String c15_webp = 'assets/category_icons/15.webp';

  static const String c16_webp = 'assets/category_icons/16.webp';

  static const String c17_webp = 'assets/category_icons/17.webp';

  static const String c18_webp = 'assets/category_icons/18.webp';

  static const String c19_webp = 'assets/category_icons/19.webp';

  static const String c2_webp = 'assets/category_icons/2.webp';

  static const String c20_webp = 'assets/category_icons/20.webp';

  static const String c21_webp = 'assets/category_icons/21.webp';

  static const String c22_webp = 'assets/category_icons/22.webp';

  static const String c23_webp = 'assets/category_icons/23.webp';

  static const String c24_webp = 'assets/category_icons/24.webp';

  static const String c25_webp = 'assets/category_icons/25.webp';

  static const String c26_webp = 'assets/category_icons/26.webp';

  static const String c27_webp = 'assets/category_icons/27.webp';

  static const String c28_webp = 'assets/category_icons/28.webp';

  static const String c29_webp = 'assets/category_icons/29.webp';

  static const String c3_webp = 'assets/category_icons/3.webp';

  static const String c30_webp = 'assets/category_icons/30.webp';

  static const String c31_webp = 'assets/category_icons/31.webp';

  static const String c32_webp = 'assets/category_icons/32.webp';

  static const String c33_webp = 'assets/category_icons/33.webp';

  static const String c34_webp = 'assets/category_icons/34.webp';

  static const String c35_webp = 'assets/category_icons/35.webp';

  static const String c36_webp = 'assets/category_icons/36.webp';

  static const String c37_webp = 'assets/category_icons/37.webp';

  static const String c38_webp = 'assets/category_icons/38.webp';

  static const String c39_webp = 'assets/category_icons/39.webp';

  static const String c4_webp = 'assets/category_icons/4.webp';

  static const String c40_webp = 'assets/category_icons/40.webp';

  static const String c41_webp = 'assets/category_icons/41.webp';

  static const String c42_webp = 'assets/category_icons/42.webp';

  static const String c43_webp = 'assets/category_icons/43.webp';

  static const String c44_webp = 'assets/category_icons/44.webp';

  static const String c45_webp = 'assets/category_icons/45.webp';

  static const String c46_webp = 'assets/category_icons/46.webp';

  static const String c47_webp = 'assets/category_icons/47.webp';

  static const String c48_webp = 'assets/category_icons/48.webp';

  static const String c49_webp = 'assets/category_icons/49.webp';

  static const String c5_webp = 'assets/category_icons/5.webp';

  static const String c50_webp = 'assets/category_icons/50.webp';

  static const String c51_webp = 'assets/category_icons/51.webp';

  static const String c52_webp = 'assets/category_icons/52.webp';

  static const String c53_webp = 'assets/category_icons/53.webp';

  static const String c54_webp = 'assets/category_icons/54.webp';

  static const String c55_webp = 'assets/category_icons/55.webp';

  static const String c56_webp = 'assets/category_icons/56.webp';

  static const String c57_webp = 'assets/category_icons/57.webp';

  static const String c58_webp = 'assets/category_icons/58.webp';

  static const String c59_webp = 'assets/category_icons/59.webp';

  static const String c6_webp = 'assets/category_icons/6.webp';

  static const String c60_webp = 'assets/category_icons/60.webp';

  static const String c61_webp = 'assets/category_icons/61.webp';

  static const String c62_webp = 'assets/category_icons/62.webp';

  static const String c63_webp = 'assets/category_icons/63.webp';

  static const String c64_webp = 'assets/category_icons/64.webp';

  static const String c65_webp = 'assets/category_icons/65.webp';

  static const String c66_webp = 'assets/category_icons/66.webp';

  static const String c67_webp = 'assets/category_icons/67.webp';

  static const String c68_webp = 'assets/category_icons/68.webp';

  static const String c69_webp = 'assets/category_icons/69.webp';

  static const String c7_webp = 'assets/category_icons/7.webp';

  static const String c70_webp = 'assets/category_icons/70.webp';

  static const String c71_webp = 'assets/category_icons/71.webp';

  static const String c72_webp = 'assets/category_icons/72.webp';

  static const String c73_webp = 'assets/category_icons/73.webp';

  static const String c74_webp = 'assets/category_icons/74.webp';

  static const String c75_webp = 'assets/category_icons/75.webp';

  static const String c76_webp = 'assets/category_icons/76.webp';

  static const String c77_webp = 'assets/category_icons/77.webp';

  static const String c78_webp = 'assets/category_icons/78.webp';

  static const String c79_webp = 'assets/category_icons/79.webp';

  static const String c8_webp = 'assets/category_icons/8.webp';

  static const String c80_webp = 'assets/category_icons/80.webp';

  static const String c81_webp = 'assets/category_icons/81.webp';

  static const String c82_webp = 'assets/category_icons/82.webp';

  static const String c83_webp = 'assets/category_icons/83.webp';

  static const String c84_webp = 'assets/category_icons/84.webp';

  static const String c85_webp = 'assets/category_icons/85.webp';

  static const String c86_webp = 'assets/category_icons/86.webp';

  static const String c87_webp = 'assets/category_icons/87.webp';

  static const String c88_webp = 'assets/category_icons/88.webp';

  static const String c89_webp = 'assets/category_icons/89.webp';

  static const String c9_webp = 'assets/category_icons/9.webp';

  static const String c90_webp = 'assets/category_icons/90.webp';

  static const String c91_webp = 'assets/category_icons/91.webp';

  static const String c92_webp = 'assets/category_icons/92.webp';

  static const String c93_webp = 'assets/category_icons/93.webp';

  static const String c94_webp = 'assets/category_icons/94.webp';

  static const String c95_webp = 'assets/category_icons/95.webp';

  static const String c96_webp = 'assets/category_icons/96.webp';

  static const String c97_webp = 'assets/category_icons/97.webp';

  static const String c98_webp = 'assets/category_icons/98.webp';

  static const String c99_webp = 'assets/category_icons/99.webp';

  static const String crow_front_premium_png = 'assets/crow-front-premium.png';
}
