import 'package:easy_localization/easy_localization.dart';

enum Categories {
  general(key: 'general', isPremium: false),
  favorites(key: 'favorites', isPremium: false),
  myquotes(key: 'myquotes', isPremium: false),
  art(key: 'art', isPremium: false),
  dreams(key: 'dreams', isPremium: false),
  enjoythemoment(key: 'enjoy_the_moment', isPremium: false),
  imagination(key: 'imagination', isPremium: true),
  inspirational(key: 'inspirational', isPremium: true),
  life(key: 'life', isPremium: true),
  music(key: 'music', isPremium: true),
  newbeginnings(key: 'new_beginnings', isPremium: true),
  thankful(key: 'thankful', isPremium: true),
  time(key: 'time', isPremium: true),
  bestrong(key: 'be_strong', isPremium: false),
  education(key: 'education', isPremium: false),
  courage(key: 'courage', isPremium: true),
  experience(key: 'experience', isPremium: true),
  growth(key: 'growth', isPremium: true),
  learning(key: 'learning', isPremium: true),
  motivational(key: 'motivational', isPremium: false),
  power(key: 'power', isPremium: true),
  beyourself(key: 'be_yourself', isPremium: true),
  startchange(key: 'start_change', isPremium: true),
  equality(key: 'equality', isPremium: false),
  faith(key: 'faith', isPremium: false),
  freedom(key: 'freedom', isPremium: false),
  minimalism(key: 'minimalism', isPremium: true),
  patience(key: 'patience', isPremium: true),
  philosophy(key: 'philosophy', isPremium: true),
  positivethinking(key: 'positive_thinking', isPremium: true),
  trust(key: 'trust', isPremium: true),
  truth(key: 'truth', isPremium: true),
  wisdom(key: 'wisdom', isPremium: true),
  business(key: 'business', isPremium: true),
  computer(key: 'computer', isPremium: false),
  entrepreneurs(key: 'entrepreneurs', isPremium: true),
  finance(key: 'finance', isPremium: false),
  intelligence(key: 'intelligence', isPremium: true),
  leadership(key: 'leadership', isPremium: true),
  money(key: 'money', isPremium: false),
  success(key: 'success', isPremium: true),
  technology(key: 'technology', isPremium: true),
  work(key: 'work', isPremium: true),
  bodybuilding(key: 'bodybuilding', isPremium: false),
  health(key: 'health', isPremium: false),
  loveyourself(key: 'love_yourself', isPremium: true),
  selfdiscipline(key: 'self_discipline', isPremium: true),
  sports(key: 'sports', isPremium: true),
  strength(key: 'strength', isPremium: true),
  weightloss(key: 'weight_loss', isPremium: false),
  workout(key: 'work_out', isPremium: true),
  chance(key: 'chance', isPremium: true),
  knowledge(key: 'knowledge', isPremium: true),
  funny(key: 'funny', isPremium: false),
  history(key: 'history', isPremium: true),
  pet(key: 'pet', isPremium: false),
  poetry(key: 'poetry', isPremium: true),
  science(key: 'science', isPremium: true),
  space(key: 'space', isPremium: false),
  travel(key: 'travel', isPremium: true),
  communication(key: 'communication', isPremium: false),
  dating(key: 'dating', isPremium: true),
  fallinglove(key: 'falling_love', isPremium: true),
  family(key: 'family', isPremium: false),
  friendship(key: 'friendship', isPremium: true),
  jealousy(key: 'jealousy', isPremium: true),
  marriage(key: 'marriage', isPremium: true),
  relations(key: 'relations', isPremium: true),
  romantic(key: 'romantic', isPremium: true),
  society(key: 'society', isPremium: false),
  attitude(key: 'attitude', isPremium: true),
  forgiveness(key: 'forgiveness', isPremium: true),
  calm(key: 'calm', isPremium: false),
  happiness(key: 'happiness', isPremium: true),
  hope(key: 'hope', isPremium: true),
  innerpeace(key: 'inner_peace', isPremium: true),
  nature(key: 'nature', isPremium: false),
  respect(key: 'respect', isPremium: true),
  sympathy(key: 'sympathy', isPremium: false),
  angercontrol(key: 'anger_control', isPremium: true),
  dissappointment(key: 'dissappointment', isPremium: true),
  failure(key: 'failure', isPremium: true),
  fear(key: 'fear', isPremium: true),
  haters(key: 'haters', isPremium: true),
  heartbroken(key: 'heartbroken', isPremium: false),
  loneliness(key: 'loneliness', isPremium: false),
  pain(key: 'pain', isPremium: false),
  sadness(key: 'sadness', isPremium: true),
  uncertainty(key: 'uncertainty', isPremium: true),
  god(key: 'god', isPremium: false),
  religion(key: 'religion', isPremium: false);

  const Categories({required this.key, required this.isPremium});
  final String key;
  final bool isPremium;

  String get iconPath => 'assets/new_category_icons/$key.webp';

  String get name => 'categoriesKey.$key'.tr();
}
